#pragma once
#define MAX_NAME 20
#define MAX_SESSIONId 20
#define MAX_SESSION 100
#define MAX_PSSWD 20
#define MAX_USR 1000
#define MAX_QUERY (MAX_NAME+MAX_SESSIONId)*1000+(MAX_SESSIONId*100)+5000

enum WEIGHT{
    REGESTER,
    HALL,
    SESSION
};

